#!/bin/bash

# GitHub 리포지토리 초기 설정 및 푸시 가이드

echo "======================================"
echo "🔧 GitHub 리포지토리 초기 설정"
echo "======================================"
echo ""

# 1. 현재 상태 확인
echo "📊 1. 현재 Git 상태 확인"
echo "   브랜치: $(git branch --show-current)"
echo "   커밋 수: $(git log --oneline | wc -l)"
echo "   리모트: $(git remote get-url origin)"
echo ""

# 2. 가이드 출력
echo "======================================"
echo "📝 GitHub 빈 리포지토리 초기 설정 방법"
echo "======================================"
echo ""
echo "문제: GitHub 리포지토리가 비어있어 Vercel이 연결할 수 없습니다."
echo ""
echo "해결 방법 (2가지 옵션):"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "옵션 1: 강제 푸시 (추천) ⭐"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. GitHub Personal Access Token 준비"
echo "   👉 https://github.com/settings/tokens"
echo "   - 'Generate new token (classic)' 클릭"
echo "   - 권한: repo 체크"
echo "   - 토큰 복사 (한 번만 보임!)"
echo ""
echo "2. 터미널에서 실행:"
echo ""
echo "   cd /home/user/webapp"
echo "   git push -u origin main --force"
echo ""
echo "   (GitHub 사용자명과 토큰 입력 요청 시 입력)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "옵션 2: GitHub Desktop 사용 (쉬움) 💻"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. GitHub Desktop 다운로드"
echo "   👉 https://desktop.github.com/"
echo ""
echo "2. GitHub Desktop에서:"
echo "   - File → Add Local Repository"
echo "   - /home/user/webapp 폴더 선택"
echo "   - 'Publish repository' 클릭"
echo "   - Repository name: myungdong-igaja"
echo "   - 'Publish repository' 버튼 클릭"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "옵션 3: Git Credential 설정 후 푸시"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Git credential helper 설정:"
echo ""
echo "   git config --global credential.helper store"
echo "   git push -u origin main"
echo ""
echo "   (첫 번째 푸시 시 사용자명과 토큰 입력)"
echo ""
echo "2. 이후 자동으로 저장됨"
echo ""
echo "======================================"
echo "✅ Push 성공 후 다음 단계"
echo "======================================"
echo ""
echo "1. https://vercel.com 접속"
echo "2. 'New Project' 클릭"
echo "3. 'myungdong-igaja' 리포지토리 선택"
echo "4. 설정:"
echo "   - Framework: Other"
echo "   - Build Command: (비워두기)"
echo "   - Output Directory: ./"
echo "5. 'Deploy' 클릭!"
echo ""
echo "======================================"
echo "❓ 여전히 문제가 있다면"
echo "======================================"
echo ""
echo "GitHub 리포지토리를 삭제하고 다시 만들기:"
echo ""
echo "1. https://github.com/paulslife2017-hue/myungdong-igaja"
echo "2. Settings → 맨 아래 'Delete this repository'"
echo "3. 새 리포지토리 생성:"
echo "   - Repository name: myungdong-igaja"
echo "   - Public 선택"
echo "   - ❌ 'Add a README file' 체크 해제 (중요!)"
echo "   - Create repository"
echo ""
echo "4. 터미널에서:"
echo ""
echo "   cd /home/user/webapp"
echo "   git remote set-url origin https://github.com/paulslife2017-hue/myungdong-igaja.git"
echo "   git push -u origin main --force"
echo ""
echo "======================================"
echo ""
echo "💡 추천: GitHub Desktop을 사용하면 가장 쉽습니다!"
echo ""
